/-
Copyright (c) 2026 STRING THEORY Formalization Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formalized World Reconstruction
-/
module

public import World.Basic

/-!
# World.Entropy — The Flattening Entropy

This module formalises §5 (Entropy Theory) of the Formalized World Model.

The source document asserts, as its highest axiom ("Axiom of Flattening"), that the
universe's entropy is *regularisation*: differences are averaged, structure is
compressed toward uniformity, local extrema are dissolved into a global
minimum-information state.

The formalisation choice made here is:

> `S_W := S_Shannon` (in nats) on probability weights over microstates, and
> *flattening* is the statement that `S_W` is **maximised, uniquely, by the uniform
> weight**.

Everything in this file is a theorem about real numbers. It is **not** an assertion
about our universe. `flattening_max_entropy` is the rigorous content of "uniformity
maximises entropy"; whether any *physical* process reaches that maximiser is a
separate claim, and in real physics it is **false for gravity** (gravitational
clumping raises total entropy). See `audit/entropy_theory.md` §3 and the
Consistency Audit.

## The Bregman divergence `D`

The whole module is organised around one auxiliary quantity, the *Bregman
divergence*

> `D x y = x·log(x/y) - x + y`,

which is the standard `f`-divergence generated by `f x = x·log x - x`. It is
nonnegative for all `x, y ≥ 0`, and zero exactly on `x = y`. Summing `D` against the
uniform weight is exactly the entropy deficit:

> `∑ᵢ D (p.w i) (1/n) = entropy p + log n`.

Both the bound `entropy p ≤ log n` and the *uniqueness* of the maximiser are then
immediate from the two properties of `D`. This is the standard proof of Gibbs'
inequality and it makes the equality case airtight.

## Sign conventions (correction log)

A first draft of this file stated the pointwise Gibbs inequality with the sign
reversed. The error is instructive, because the scalar bound `log t ≤ t - 1` makes
the correct direction easy to misread:

* For `x, y > 0`: `log (x/y) = -log (y/x) ≥ -(y/x - 1) = 1 - y/x = (x-y)/x`.
* Hence `x·log (x/y) ≥ x - y`, i.e. `x·log x ≥ x·log y + (x - y)`. **(lower bound)**
* The reversed inequality `x·log x ≤ x·log y + (x - y)` is **false** whenever
  `x ≠ y` (numerically, `x = 3, y = 1`: `3·log 3 ≈ 3.296 > 2`).

In terms of `D`, the correct statement is simply `0 ≤ D x y`.
-/

@[expose] public section

namespace World

open Finset Real

/-! ## The Bregman divergence -/

/-- **Definition.** `D x y = x·log(x/y) - x + y`, the Bregman divergence of
`x ↦ x·log x - x`. With Lean's conventions `log 0 = 0` and `z / 0 = 0`, the formula
extends continuously to `x = 0` and `y ≤ 0`, so no case split appears in the
definition itself.

This is the world model's *local flattening cost*: the amount by which the weight `x`
fails to equal the reference weight `y`. -/
noncomputable def bregDiv (x y : ℝ) : ℝ := x * Real.log (x / y) - x + y

/-- **Gibbs' inequality, pointwise form (THEOREM).** For positive `x, y`,
`x·log y + (x - y) ≤ x·log x`. -/
theorem mul_log_ge {x y : ℝ} (hx : 0 < x) (hy : 0 < y) :
    x * Real.log y + (x - y) ≤ x * Real.log x := by
  have h1 : Real.log (y / x) ≤ y / x - 1 := Real.log_le_sub_one_of_pos (div_pos hy hx)
  have h2 : Real.log (x / y) = -Real.log (y / x) := by
    rw [Real.log_div hx.ne' hy.ne', Real.log_div hy.ne' hx.ne']; ring
  have h2b : (x - y) / x = 1 - y / x := by field_simp
  have h3 : (x - y) / x ≤ Real.log (x / y) := by rw [h2, h2b]; linarith
  have h4 : x * ((x - y) / x) ≤ x * Real.log (x / y) := mul_le_mul_of_nonneg_left h3 hx.le
  have h5 : x * ((x - y) / x) = x - y := by field_simp
  have h6 : x - y ≤ x * Real.log (x / y) := by linarith [h4, h5.symm.le, h5.le]
  have h7 : Real.log (x / y) = Real.log x - Real.log y := Real.log_div hx.ne' hy.ne'
  rw [h7] at h6
  nlinarith [h6]

/-- **Strict Gibbs, pointwise form (THEOREM).** If `x ≠ y` the inequality is strict. -/
theorem mul_log_gt {x y : ℝ} (hx : 0 < x) (hy : 0 < y) (hxy : x ≠ y) :
    x * Real.log y + (x - y) < x * Real.log x := by
  have hyx : y / x ≠ 1 := by
    intro h
    have : y = x := by field_simp at h; linarith
    exact hxy this.symm
  have h1 : Real.log (y / x) < y / x - 1 := Real.log_lt_sub_one_of_pos (div_pos hy hx) hyx
  have h2 : Real.log (x / y) = -Real.log (y / x) := by
    rw [Real.log_div hx.ne' hy.ne', Real.log_div hy.ne' hx.ne']; ring
  have h2b : (x - y) / x = 1 - y / x := by field_simp
  have h3 : (x - y) / x < Real.log (x / y) := by rw [h2, h2b]; linarith
  have h4 : x * ((x - y) / x) < x * Real.log (x / y) := mul_lt_mul_of_pos_left h3 hx
  have h5 : x * ((x - y) / x) = x - y := by field_simp
  have h6 : x - y < x * Real.log (x / y) := by linarith [h4, h5.symm.le, h5.le]
  have h7 : Real.log (x / y) = Real.log x - Real.log y := Real.log_div hx.ne' hy.ne'
  rw [h7] at h6
  nlinarith [h6]

/-- **LEMMA.** `x - y ≤ x·log(x/y)` for positive `x, y`. -/
theorem sub_le_mul_log_div {x y : ℝ} (hx : 0 < x) (hy : 0 < y) :
    x - y ≤ x * Real.log (x / y) := by
  have h2 : Real.log (x / y) = -Real.log (y / x) := by
    rw [Real.log_div hx.ne' hy.ne', Real.log_div hy.ne' hx.ne']; ring
  have h2b : (x - y) / x = 1 - y / x := by field_simp
  have h3 : (x - y) / x ≤ Real.log (x / y) := by
    have h1 : Real.log (y / x) ≤ y / x - 1 := Real.log_le_sub_one_of_pos (div_pos hy hx)
    rw [h2, h2b]; linarith
  have hm := mul_le_mul_of_nonneg_left h3 hx.le
  have hxy : x * ((x - y) / x) = x - y := by field_simp
  linarith [hm, hxy.symm.le, hxy.le]

/-- **THEOREM (T0).** `D` is nonnegative whenever `y > 0`. -/
theorem bregDiv_nonneg {x y : ℝ} (hx : 0 ≤ x) (hy : 0 < y) : 0 ≤ bregDiv x y := by
  rcases eq_or_lt_of_le hx with h0 | h0
  · rw [← h0]
    simp [bregDiv, Real.log_zero]
    linarith [hy]
  · have h := sub_le_mul_log_div h0 hy
    rw [bregDiv]
    nlinarith [h]

/-- **THEOREM (T0').** `D` vanishes exactly when the weights agree. -/
theorem bregDiv_eq_zero_iff {x y : ℝ} (hx : 0 ≤ x) (hy : 0 < y) :
    bregDiv x y = 0 ↔ x = y := by
  constructor
  · intro h
    rcases eq_or_lt_of_le hx with h0 | h0
    · rw [← h0] at h
      simp [bregDiv, Real.log_zero] at h
      linarith [h0, h]
    · -- `x·log(x/y) = x - y` is the equality case of `sub_le_mul_log_div`.
      have hkey := sub_le_mul_log_div h0 hy
      have hlog : Real.log (x / y) = 1 - y / x := by
        have h2 : Real.log (x / y) = -Real.log (y / x) := by
          rw [Real.log_div h0.ne' hy.ne', Real.log_div hy.ne' h0.ne']; ring
        have h2b : (x - y) / x = 1 - y / x := by field_simp
        have h3 : (x - y) / x ≤ Real.log (x / y) := by
          have h1 : Real.log (y / x) ≤ y / x - 1 := Real.log_le_sub_one_of_pos (div_pos hy h0)
          rw [h2, h2b]; linarith
        have hm := mul_le_mul_of_nonneg_left h3 h0.le
        have hxy : x * ((x - y) / x) = x - y := by field_simp
        have h4 : x - y ≤ x * Real.log (x / y) := by linarith [hm, hxy.symm.le, hxy.le]
        have h5 : x * Real.log (x / y) = x - y := by
          rw [bregDiv] at h; linarith [h, hkey, h4]
        rw [h2] at h5
        have h6 : x * (1 - y / x) = x - y := by field_simp
        nlinarith [h5, h6]
      -- Equality in `log t ≤ t - 1` forces `y/x = 1`.
      have h2 : Real.log (x / y) = -Real.log (y / x) := by
        rw [Real.log_div h0.ne' hy.ne', Real.log_div hy.ne' h0.ne']; ring
      rw [h2] at hlog
      have ht : y / x = 1 := by
        by_contra hne
        have hlt : Real.log (y / x) < y / x - 1 :=
          Real.log_lt_sub_one_of_pos (div_pos hy h0) hne
        linarith
      field_simp at ht
      linarith
  · intro h
    rw [h, bregDiv]
    have h1 : Real.log (y / y) = 0 := by rw [div_self hy.ne', Real.log_one]
    rw [h1]; ring

/-! ## Shannon entropy -/

/-- **Definition (Fundamental Definition F2).** The entropy of a statistical state,
in nats. This is the world model's `S_W`.
Real physics: the Gibbs entropy with `k_B = 1`. -/
noncomputable def entropy {ι : Type*} [Fintype ι] (p : ProbDist ι) : ℝ :=
  -∑ i, p.w i * Real.log (p.w i)

/-- Entropy in units of `k_B`: `S = k_B · S_W`. -/
noncomputable def entropyKB {ι : Type*} [Fintype ι] (p : ProbDist ι) (kB : ℝ) : ℝ :=
  kB * entropy p

/-- **THEOREM (T1a).** Entropy is nonnegative, since `x·log x ≤ 0` on `[0,1]`. -/
theorem entropy_nonneg {ι : Type*} [Fintype ι] (p : ProbDist ι) : 0 ≤ entropy p := by
  have h : ∀ i ∈ (Finset.univ : Finset ι), p.w i * Real.log (p.w i) ≤ 0 := by
    intro i _
    have h1 : Real.log (p.w i) ≤ 0 := by
      rcases eq_or_lt_of_le (p.nonneg i) with h0 | h0
      · rw [← h0]; simp
      · exact Real.log_nonpos (p.nonneg i) (p.le_one i)
    exact mul_nonpos_of_nonneg_of_nonpos (p.nonneg i) h1
  have := Finset.sum_nonpos h
  simp only [entropy]
  linarith

/-- **LEMMA.** The entropy of a constant distribution with weight `c` is
`log (card ι)`, given `c · card ι = 1`. -/
theorem const_entropy {ι : Type*} [Fintype ι] [Nonempty ι] {c : ℝ} (hc : 0 < c)
    (hsum : c * (Fintype.card ι : ℝ) = 1) :
    entropy (⟨fun _ => c, fun _ => hc.le,
      by rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul', hsum]⟩ : ProbDist ι)
      = Real.log (Fintype.card ι) := by
  have hcard_pos : (0 : ℝ) < (Fintype.card ι : ℝ) := by exact_mod_cast Fintype.card_pos
  have hcard_ne : (Fintype.card ι : ℝ) ≠ 0 := ne_of_gt hcard_pos
  have hlog : Real.log c = -Real.log (Fintype.card ι) := by
    have h1 : c = (Fintype.card ι : ℝ)⁻¹ := by
      field_simp at hsum ⊢; linarith
    rw [h1, Real.log_inv]
  have hc' : c = (Fintype.card ι : ℝ)⁻¹ := by
    field_simp at hsum ⊢; linarith
  simp only [entropy, Finset.sum_const, Finset.card_univ, nsmul_eq_mul', hlog]
  rw [show -(c * -Real.log ↑(Fintype.card ι) * ↑(Fintype.card ι))
        = c * Real.log ↑(Fintype.card ι) * ↑(Fintype.card ι) by ring, hc']
  rw [mul_assoc, mul_comm (Real.log ↑(Fintype.card ι)) (↑(Fintype.card ι)),
    ← mul_assoc, inv_mul_cancel₀ hcard_ne, one_mul]

/-- **THEOREM (T1, Gibbs' inequality / maximal entropy).**

For any probability weight `p` on a finite nonempty type, `entropy p ≤ log (card ι)`,
with equality **if and only if** `p` is the uniform weight. This is the rigorous
content of the Flattening Axiom: uniformity is the *unique* entropy maximiser.

A theorem of real mathematics. It says nothing about whether any physical process
reaches the maximiser. -/
theorem flattening_max_entropy {ι : Type*} [Fintype ι] [Nonempty ι] (p : ProbDist ι) :
    entropy p ≤ Real.log (Fintype.card ι) ∧
      (entropy p = Real.log (Fintype.card ι) ↔ p = ProbDist.uniform ι) := by
  classical
  have hcard_pos : (0 : ℝ) < (Fintype.card ι : ℝ) := by exact_mod_cast Fintype.card_pos
  set y : ℝ := (Fintype.card ι : ℝ)⁻¹ with hy_def
  have hy_pos : 0 < y := by rw [hy_def]; positivity
  have hlogy : Real.log y = -Real.log (Fintype.card ι) := by rw [hy_def, Real.log_inv]
  have hycard : y * (Fintype.card ι : ℝ) = 1 := by rw [hy_def]; field_simp
  have hcard_ne : (Fintype.card ι : ℝ) ≠ 0 := ne_of_gt hcard_pos
  -- The uniform distribution, written with reference weight `y`.
  have hpuni_eq : (⟨fun _ : ι => (Fintype.card ι : ℝ)⁻¹, fun _ => by positivity,
      by simp [Finset.sum_const, Finset.card_univ, hcard_ne]⟩ : ProbDist ι)
      = ProbDist.uniform ι := rfl
  -- Pointwise Gibbs bound.
  have hpt : ∀ i : ι, p.w i * Real.log y + (p.w i - y) ≤ p.w i * Real.log (p.w i) := by
    intro i
    rcases eq_or_lt_of_le (p.nonneg i) with h0 | h0
    · rw [← h0]; simp; linarith [hy_pos]
    · exact mul_log_ge h0 hy_pos
  have hleft : ∑ i, (p.w i * Real.log y + (p.w i - y)) = -Real.log (Fintype.card ι) := by
    rw [Finset.sum_add_distrib, Finset.sum_sub_distrib, Finset.sum_const,
      Finset.card_univ, ← Finset.sum_mul, p.sum_eq_one, one_mul, hlogy]
    rw [nsmul_eq_mul', hycard]
    ring
  have hbound : entropy p ≤ Real.log (Fintype.card ι) := by
    have hsum := Finset.sum_le_sum fun i (_ : i ∈ Finset.univ) => hpt i
    rw [hleft] at hsum
    simp only [entropy]
    linarith
  refine ⟨hbound, ⟨fun heq => ?_, fun heq => ?_⟩⟩
  · -- Equality forces every weight to equal `y`.
    by_contra hcon
    rw [← hpuni_eq] at hcon
    have hne : p.w ≠ (fun _ : ι => (Fintype.card ι : ℝ)⁻¹) := fun hw' =>
      hcon (by cases p with
            | mk w hn hs => simp_all)
    obtain ⟨j, hj⟩ := Function.ne_iff.mp hne
    have hstrict : p.w j * Real.log y + (p.w j - y) < p.w j * Real.log (p.w j) := by
      rcases eq_or_lt_of_le (p.nonneg j) with h0 | h0
      · rw [← h0]; simp; linarith [hy_pos]
      · refine mul_log_gt h0 hy_pos (fun hjy => hj ?_)
        rw [hjy, hy_def]
    have hlt := Finset.sum_lt_sum (fun i _ => hpt i) ⟨j, Finset.mem_univ j, hstrict⟩
    rw [hleft] at hlt
    simp only [entropy] at heq
    linarith
  · -- The uniform weight attains the bound: it is the constant distribution `y`.
    subst heq
    exact const_entropy hy_pos hycard

/-- Entropy is maximal exactly at uniformity. -/
theorem entropy_le_log_card {ι : Type*} [Fintype ι] [Nonempty ι] (p : ProbDist ι) :
    entropy p ≤ Real.log (Fintype.card ι) := (flattening_max_entropy p).1

/-- The uniform weight attains the maximum. -/
@[simp] theorem entropy_uniform {ι : Type*} [Fintype ι] [Nonempty ι] :
    entropy (ProbDist.uniform ι) = Real.log (Fintype.card ι) :=
  (flattening_max_entropy (ProbDist.uniform ι)).2.mpr rfl

end World
